os:
  - osx
  - linux
env:
  - GAUGE_TELEMETRY_ENABLED=false
before_install:
  - mozroots --import --sync
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install Caskroom/cask/java; fi
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/gauge/gauge-deb nightly main'
    packages:
      - oracle-java8-set-default
      - maven
      - gauge
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated maven || brew upgrade maven; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install_latest_gauge_nightly.sh; fi
  - mvn -version
  - gauge version
  - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> $HOME/.gauge/config/gauge.properties

language: csharp
mono:
  - 5.0.1
dotnet: 2.1.3
cache:
  directories:
  - $HOME/.m2
script:
  - ./build.sh BuildInstallFT